# Generated by Django 4.2.1 on 2023-05-31 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('passengers_amount', models.PositiveIntegerField()),
            ],
        ),
    ]
